Repository Robsonmxms/A-Peter-s-Journey, pull requests merged in 2023-04, with the labels that each got.

#1 Mergiando as POC para o projeto
  .DS_Store
  APetersJourney.xcodeproj/project.pbxproj
  APetersJourney.xcodeproj/xcshareddata/xcschemes/APetersJourney.xcscheme
  APetersJourney/Presentation/Maze/Scene/MazeScene.swift
  APetersJourney/Presentation/Maze/View/MazeView.swift
  APetersJourney/Utils/Circle3D.swift
  APetersJourney/Utils/SphereSKNode.swift
  APetersJourneyTests/APetersJourneyTests.swift
Labels: enhancement

#4 🧪 testes unitarios das classes construidas
  .DS_Store
  APetersJourney.xcodeproj/project.pbxproj
  APetersJourneyTests/APetersJourneyTests.swift
  APetersJourneyTests/Circle3DTest.swift
  APetersJourneyTests/CircleNodeTest.swift
  APetersJourneyTests/MazeTest.swift
  APetersJourneyTests/SphereSKNodeTest.swift
Labels: documentation

#5 🧾 adicionando README e LICENSE
  APetersJourney.xcodeproj/xcshareddata/xcschemes/APetersJourney.xcscheme
  LICENSE.md
  README.md
Labels: documentation

#6 🕹️ adicionando as funções de vencer e reiniciar o
  .DS_Store
  APetersJourney.xcodeproj/project.pbxproj
  APetersJourney/Presentation/Maze/Scene/MazeScene.swift
Labels: enhancement

#10 💄 AppIcon Select
  .DS_Store
  .gitignore
  APetersJourney/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  APetersJourney/Resources/Assets.xcassets/AppIcon.appiconset/appstore1024.png
  APetersJourney/Resources/Assets.xcassets/AppIcon.appiconset/ipad152.png
  APetersJourney/Resources/Assets.xcassets/AppIcon.appiconset/ipad76.png
  APetersJourney/Resources/Assets.xcassets/AppIcon.appiconset/ipadNotification20.png
  APetersJourney/Resources/Assets.xcassets/AppIcon.appiconset/ipadNotification40.png
  APetersJourney/Resources/Assets.xcassets/AppIcon.appiconset/ipadPro167.png
  APetersJourney/Resources/Assets.xcassets/AppIcon.appiconset/ipadSettings29.png
  APetersJourney/Resources/Assets.xcassets/AppIcon.appiconset/ipadSettings58.png
  APetersJourney/Resources/Assets.xcassets/AppIcon.appiconset/ipadSpotlight40.png
  APetersJourney/Resources/Assets.xcassets/AppIcon.appiconset/ipadSpotlight80.png
  APetersJourney/Resources/Assets.xcassets/AppIcon.appiconset/iphone120.png
  APetersJourney/Resources/Assets.xcassets/AppIcon.appiconset/iphone180.png
  APetersJourney/Resources/Assets.xcassets/AppIcon.appiconset/mac1024.png
  APetersJourney/Resources/Assets.xcassets/AppIcon.appiconset/mac128.png
  APetersJourney/Resources/Assets.xcassets/AppIcon.appiconset/mac16.png
  APetersJourney/Resources/Assets.xcassets/AppIcon.appiconset/mac256.png
  APetersJourney/Resources/Assets.xcassets/AppIcon.appiconset/mac32.png
  APetersJourney/Resources/Assets.xcassets/AppIcon.appiconset/mac512.png
  APetersJourney/Resources/Assets.xcassets/AppIcon.appiconset/mac64.png
  APetersJourney/Resources/Assets.xcassets/AppIcon.appiconset/notification40.png
  APetersJourney/Resources/Assets.xcassets/AppIcon.appiconset/notification60.png
  APetersJourney/Resources/Assets.xcassets/AppIcon.appiconset/settings58.png
  APetersJourney/Resources/Assets.xcassets/AppIcon.appiconset/settings87.png
  APetersJourney/Resources/Assets.xcassets/AppIcon.appiconset/spotlight120.png
  APetersJourney/Resources/Assets.xcassets/AppIcon.appiconset/spotlight80.png
Labels: enhancement

#12 Fixing .gitignore: removing .DS_Store files
  .DS_Store
  APetersJourney/.DS_Store
  APetersJourney/Presentation/.DS_Store
  APetersJourney/Resources/.DS_Store
Labels: bug

#14 implementation of InitialView
  APetersJourney.xcodeproj/project.pbxproj
  APetersJourney/Application/GameBoard.swift
  APetersJourney/Presentation/Maze/Scene/InitialScene.swift
  APetersJourney/Presentation/Maze/View/MazeView.swift
  APetersJourney/Resources/Assets.xcassets/background.imageset/Contents.json
  APetersJourney/Resources/Assets.xcassets/background.imageset/background@2x.png
  APetersJourney/Resources/Assets.xcassets/peixe1.imageset/Contents.json
  APetersJourney/Resources/Assets.xcassets/peixe1.imageset/peixe1.png
Labels: enhancement

#19 OnBoard Screen implementada
  APetersJourney.xcodeproj/project.pbxproj
  APetersJourney/Application/GameBoard.swift
  APetersJourney/Application/PeterJourneyApp.swift
  APetersJourney/Presentation/Menu/MazeModel.swift
  APetersJourney/Presentation/Menu/Scene/MazeScene.swift
  APetersJourney/Presentation/Menu/Scene/MenuScene.swift
  APetersJourney/Presentation/Menu/View/MenuView.swift
  APetersJourney/Presentation/OnBoard/View/Components/OnBoardImage.swift
  APetersJourney/Presentation/OnBoard/View/OnBoardView.swift
  APetersJourney/Resources/Assets.xcassets/boy.imageset/Contents.json
  APetersJourney/Resources/Assets.xcassets/boy.imageset/boy.png
  APetersJourney/Resources/Assets.xcassets/doll.imageset/Contents.json
  APetersJourney/Resources/Assets.xcassets/doll.imageset/doll.png
  APetersJourney/Resources/Assets.xcassets/image1.imageset/Contents.json
  APetersJourney/Resources/Assets.xcassets/image1.imageset/image1.png
  APetersJourney/Resources/Assets.xcassets/mom.imageset/Contents.json
  APetersJourney/Resources/Assets.xcassets/mom.imageset/mom.png
Labels: enhancement
